# Generated by Django 3.2.19 on 2024-09-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipping_Table', '0002_alter_shipping_table_shipping_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_table',
            name='shipping_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
