# Generated by Django 3.2.19 on 2024-09-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipping_Table', '0003_alter_shipping_table_shipping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping_table',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipping_table',
            name='first_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipping_table',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='shipping_table',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
