# Generated by Django 3.2.19 on 2024-09-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipping_Table', '0004_auto_20240911_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_table',
            name='city',
            field=models.CharField(default='temp', max_length=100),
        ),
        migrations.AlterField(
            model_name='shipping_table',
            name='first_line',
            field=models.CharField(default='temp', max_length=255),
        ),
        migrations.AlterField(
            model_name='shipping_table',
            name='pincode',
            field=models.CharField(default='temp', max_length=6),
        ),
        migrations.AlterField(
            model_name='shipping_table',
            name='state',
            field=models.CharField(default='temp', max_length=100),
        ),
    ]
